### ISSUE TITLE
Mode selection with gamepad 'select' button.

### ISSUE THREAD

**Issue by ajtrowell** [ImaginaryRadicals/ftc_app#20]
Create logic to change 'modes' by pressing the 'select' button the gamepad.  

Create a RobotMode enum with several placeholder modes, like MODE_A and MODE_B.

Use the Signal class method 'risingEdge()' to make sure that the mode is only changes once per button press.

Eventually, these modes could be used to implement a SLOW_SPEED and NORMAL_SPEED mode. Alternatively, it could aid testing by allowing us to switch seamlessly between TELEOP_MODE and AUTO_MODE.

**Comment by joshwinebrener** [comment]
Used "back" button, rather than select button.  Select was being used for something else.
